Field disabled state follow form disabled state
melohagan/budibase-component-kasper-date-picker pull request #13
Opened 2023-04-17 16:11 UTC by lolcabanon

Field will be disabled if the containing form is disabled.

2023-04-17 16:50 UTC, lolcabanon commented
Ok put this one on hold there seems to be an issue...

I have an error `TypeError: Cannot read properties of undefined (reading 'value')` unless I disable an re-enable the form.

![image](https://user-images.githubusercontent.com/90099349/232555293-4805fc3c-7a9a-4b79-a73d-8d1903bc4cb4.png)

After I disable an re-enable the form it seems to work all good tho...

2023-04-17 17:16 UTC, lolcabanon commented
Ok after a second checkup, it seems to work flawlessly as is with Budibase `2.5.2`.

Weird behaviour in my [last comment](#issuecomment-1511734994) only happen in version `2.4.31` (from that I cant test).

2023-04-18 07:36 UTC, melohagan commented on src/Component.svelte
> -      {disabled}
I think this needs to be an or, i.e.

`disabled={fieldState?.disabled || disabled}`

2023-04-18 07:37 UTC, melohagan requested changes
Thanks for adding this - just needs a little tweak!

2023-04-18 20:52 UTC, lolcabanon commented
Should it really be `||` ?

According to [MDN about `??`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing) :

>The nullish coalescing (??) operator is a logical operator that returns its right-hand side operand when its left-hand side operand is [null](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/null) or [undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined), and otherwise returns its left-hand side operand.
>[...]
>The nullish coalescing operator can be seen as a special case of the [logical OR (||) operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR). The latter returns the right-hand side operand if the left operand is any [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) value, not only null or undefined. In other words, if you use || to provide some default value to another variable foo, you may encounter unexpected behaviors if you consider some falsy values as usable (e.g., '' or 0).

I think if `fieldState.disabled` is `false` it should return false indeed. But if either `fieldState` or `fieldState.disabled` are `undefined` it should then return `disabled` (local variable defaulting to `false`).

And by adding `?.` it is safe to test as `fieldState?.disabled` will return `undefined` if `fieldState` or `fieldState.disabled` are `null` or `undefined`.

2023-04-20 10:53 UTC, melohagan approved these changes
Tested it locally and works well! Thank you 😄

2023-04-20 10:53 UTC, merged